---
title: "Policies"
output:
  pdf_document:
    toc: no
  html_document:
    theme: paper
    toc: yes
    toc_depth: 3
    toc_float: yes
---
### Communication
I will hold **weekly office hours on Wednesdays at 10-11 and Thursdays at 11-12 in SSH 1252**. If these times do not work for you, please [schedule a meeting](http://ekmerchant.youcanbook.me) at another time. My office is not easy to find, but [this map](http://emilyklancher.com/Map_SSH1252.pdf) will help. You may also [email me](mailto:ekmerchant@ucdavis.edu) to discuss any aspect of this course. Please put the course number in the subject line of the email. I will generally respond within one business day.

### Expectations
The work for this course should take you about 16 hours per week on average, including time in class. I expect that you will attend all class meetings and arrive having done the required reading and completing any other preparatory work. Attendance and participation will account for 10% of your grade, so any absence will reduce your final grade by 0.5 points.

### Late Work
With the exception of Lab 10, there is a two-day grace period (no questions asked) for all assignments. If you will be unable to turn in your assignment by the end of the grace period, you must schedule a meeting with me to establish a timeline for completing it.

### Accommodations
I will work with the [Student Disability Center](http://sdc.ucdavis.edu) (SDC) to make accommodations for documented disabilities. All requests must be initiated through the SDC, but do let me know if your needs are not being adequately addressed. If you think you might have a disability or medical or psychological condition that affects your learning, please do not hesitate to contact the SDC for evaluation.

### Classroom Etiquette
This course will involve conversations about historical and contemporary constructions of gender, race, sexuality, and class. These conversations may be difficult, but the classroom is a safe space to discuss and write about these issues. *Scholarly disagreements are allowed and debate is encouraged, but your comments should refer to course materials, not another person.* You will learn how to support your arguments in writing and conversation with numeric data and textual references. For an up-to-date guide to appropriate and inappropriate terminology, consult the [UC Davis LGBTQIA+ Resource Center Glossary](http://lgbtqia.ucdavis.edu/educated/glossary) or the [Radical Copy Editor](http://radicalcopyeditor.com). I expect you to be courteous to yoru classmates and their ideas, to allow them to speak, and to listen to them carefully. If you think a reading or discussion may be trggering to you personally, please notify me in advance (no details necessary) so we can manage the situation to protect your physical and emotional safety.

### Academic Integrity
As in all courses at UC Davis, you will be held to the University's [Code of Academic Conduct](http://sja.ucdavis.edu/files/cac.pdf), which prohibits all forms of academic misconduct, from outright cheating or plagiarism to inadequate citation. You must acknowledge this Code of Academic Conduct for each course in which you are registered on the [Academic Participation](http://participate.ucdavis.edu) website. All work that you submit for this class must be your own and must not have been submitted for a grade in any other class without prior approval from myself and the instructor of the other class. I will report all cases of suspected misconduct to the [Office of Student Support and Judicial Affairs](http://ossja.ucdavis.edu). Please do not hesitate to ask *in advance* if you are unsure whether something you plan to do violates the code.

### Campus Resources
UC Davis offers many resources to help you cope with the challenges of college life. The [Academic Assistance and Tutoring Center](http://success.ucdavis.edu/aat/index.html) offers workshops and tutoring for writing and study skills. The [Center for Advocacy, Resources, and Education](http://care.ucdavis.edu), formerly known as the Campus Violence Prevention Program, is the on-campus, confidential resource for all students who have experienced any form of sexual or gender-based violence. The [Student Health and Counseling Services](http://shcs.ucdavis.edu) provides a range of resources for psychological and medical support. The [Office of Student Support and Judicial Affairs](https://ossja.ucdavis.edu/resources) has information about services related to food, finances, housing, and other necessities. Please do not hesitate to reach out for the help you need to succeed in college.
