---
title: "Reading Guides"
output:
  html_document:
    theme: paper
    toc: yes
    toc_depth: 3
    toc_float: yes
---
## Week 1
### [The Census, Audiences, and Publics](http://emilyklancher.com/teaching/Anderson.html)
**Margo Anderson, 2008, *Social Science History* 32: 1-18.**

This file takes some time to load and is best viewed in Safari. It includes a video clip that will not run in Chrome. Look at the images as you read, and try to see what Anderson is seeing. Do you see anything she doesn't mention?

## Week 2
###  [Minnesota Historical Census Projects](readings/Minnesota_Historical_Census.pdf) 
**Special issue of *Historical Methods*, 1995 (highlighted sections only).**

As you read, pay attention to the following things:

- What is the difference between published (aggregate, tabular) census data and unpublished census manuscripts (microdata)?
- What are the three key strengths of the IPUMS national census files?
- When and why did the census begin to collect information about individuals rather than households?
- How did disputes over slavery affect the 1850 census?
- What was the controversy over the 1870 census? Why were new questions proposed, and why did Congress resist?
- How did the audience for the census change at the end of the nineteenth century? How does this relate to last week's reading by Margo Anderson?
- How did census-taking change in 1960?
- Why is it important to get public input into the development of census schedules? How does that relate to the upcoming census in 2020?

These questions will be important for Lab 2:

- When and why were year and month of birth added to the census schedule? Did they solve the problem they were supposed to solve?
- Why are there two different coding schemes for relationship to household head? How was this relationship determined before 1880?
- What are the constructed variables? How are they constructed? What information do they provide? Why and how might you use them?

## Week 3
### [Racial Reorganization and the United States Census, 1850-1930: Mulattoes, Half-Breeds, Mixed Parentage, Hindoos, and the Mexican Race](https://doi.org/10.1017/S0898588X08000047)
**Jennifer L. Hochschild and Brenna Marea Powell, 2008, *Studies in American Political Development* 22: 59-96.**  
This is an outline of the article, with questions to guide your reading of each section. You do not have to be able to formulate a coherent answer to these questions, but these are the things you should pay attention to.

- Introduction (pp. 59-61)
  + What is the authors' main argument?
  + What are their two empirical research questions?
  + Why do they focus on the census?
  + What do the authors mean by "racial reorganization," and why did the United States experience it (according to the authors) between the Civil War and World War II?
- Theoretical framework establishing the relationship between the census and the racial order (pp. 61-65)
  + What do the authors mean by "racial order"? What are its two dimensions? How did it change over this period?
  + How does a Census contribute to creation, maintenance, and transformation of the racial order?
- Census Bureau's role in reorganizing the U.S. racial order from the 1850 census to the 1930 census (pp. 65 - 81, with subsections for the major racial categories)
  + What three general factors ("motivations") shaped the race classification in any given census? How do the authors define each one, and what role does each one play?
  + Why did the census add a "mulatto" category in 1850? Why did it drop this category in 1930?
  + What was the relationship between Asian race categories and immigration/naturalization?
  + Debates over the social and political position of European immigrants are not reflected in racial categories. Where do we see them? Why there instead of race?
  + What is the maning of the phrase "Indians not taxed" in Article 1, Section 2 of the Constitution?
  + How has U.S. policy toward Native Americans influenced the way they are classified in the census?
  + How and why did the classification of Mexican Americans change between the 1920, 1930, and 1940 censuses? What was at stake in this classification?
- Demographic change between 1850 and 1930 (pp. 82-87)
  + The authors attribute the "racial reorganization" of the 1850-1840 period to "demographic upheaval" (82). What historical events and changes do they include in that upheaval?
  + What historical events and changes stabilized the demographic and racial order after 1940?
- Conclusion (pp. 87-90)
  + Why do the authors suggest that we may again be in a period of racial reorganization?
  + This article was written 10 years ago. Do the "current" demographic and racial issues they describe still seem current? Why or why not?

## Week 4
### [Life in Industrial America](http://www.americanyawp.com/text/18-industrial-america/)
**The American Yawp.**

This is a textbook and is quite straightforward. Read to get a sense of how the kind of work people did and the industries they worked in changed over the second half of the nineteenth century and first half of the twentieth.

## Week 5
### [Women's Work and Women's Households: Gender Bias in the U.S. Census](https://www.jstor.org/stable/pdf/40970556.pdf) 
**Nancy Folbre and Marjorie Abel, 1989, *Social Research* 56: 545-569.** 

This article discusses systematic bias in the way the U.S. Census reported women's labor force participation and their role in households over the period from 1880 to 1980. As you read it, pay particular attention to the reasons why we must be skeptical about numbers derived from the Census regarding women's working lives and thier status in households. Be prepared to discuss these issues in class and in Lab 5.

### [Decapitating the U.S. Census Bureau's "Head of Household": Feminist mobilization in the 1970s](https://www.tandfonline.com/doi/pdf/10.1080/135457098338356)
**Harriet B. Presser, 1998, *Feminist Economics* 4: 145-158.**

The previous article explains that the Census Bureau did away with the "Head of Household" designation beginnning with the 1980 Census. This article explains how that change came about and is written by someone who was involved in that process. As you read it, note *when* this change came about, *who* pushed for it, *why* they thought it was important, *how* the Census Bureau responded, and *what* eventually made the change happen. This article demonstrates that the census is a constantly-evolving document (as we also saw in the Week 3 reading about race classification), and provides detail into one instance of historical change.

## Week 6
### [The Architecture of Race in American Immigration Law: A Reexamination of the Immigration Act of 1924](https://www.jstor.org/stable/pdf/2567407.pdf)
**Mae M. Ngai, 1999, *Journal of American History* 86: 67-92.**

This article is about the National Origins Act of 1924, which sharply limited immigration to the United States. You will notice many connections to the article we read by Hochschild and Powell in Week 3. As you read, pay particular attention to the following:

- What was the role of the census in establishing immigration quotas?
- How did the National Origins Act change the racial order?
- How did the Act invent the concept of nationalality?
- How did the Act change the relationship between race and nationality?
- What were the consequences for the three groups of immigrants Ngai focuses on: Europeans, Asians, and Latin Americans?

## Week 7
### [Chapter 1: A Century of Migration](http://ebookcentral.proquest.com/lib/ucdavis/detail.action?docID=413303)
**James N. Gregory, 2005, *The Southern Diaspora: How the Great Migrations of Black and White Southerners Transformed America* (Chapel Hill: University of North Carolina Press).**

As you read Chapter 1 of *The Southern Diaspora*, think about how this reading connects to our earlier readings about race, industrialization, and immigration. Focus on the following questions:

- What does Gregory mean by "Southern Diaspora"?
- Who was migrating? When? Where were they going? Why?
- How did the experience of migration out of the South differ for black and white southerners?
- How does Gregory describe the relationship between a diaspora and an individual move?
- How does Gregory utilize IPUMS data to make his points?
- Gregory does not map his data. What kind of maps would have been useful?

## Week 8
### [Ethnicity and the Boundaries of Race: Rereading Directive 15](https://doi.org/10.1162/0011526053124352)
**Victoria Hattam, 2006, *Daedalus* 134: 61-69.** 

### [Doing the Dirty Work: Gender, Race, and Reproductive Labor in Historical Perspective](https://journals.sagepub.com/doi/pdf/10.1177/0891243207300764)
**Mignon Duffy, 2007, *Gender and Society* 21: 313-336.**

## Week 9
### [Boundary Blurring? Racial Identification Among the Children of Interracial Couples](https://journals.sagepub.com/doi/pdf/10.1177/0002716218760507)
**Daniel T. Lichter and Zhenchao Qian, 2018, *Annals of the American Academy of Political and Social Science* 677: 81-94.**

## Week 10
### [The Measurement of Same-Sex Unmarried Partner Couples in the 2000 U.S. Census](https://escholarship.org/uc/item/72r1q94b)
**Dan Black et al., 2007, California Center for Population Research.**