---
title: "Schedule"
output:
  html_document:
    theme: paper
    toc: yes
    toc_depth: 3
    toc_float: yes
---

$~$

## Week 1
### Tuesday 1.8.19: Introduction to the course and JupyterHub
- [Jupyter Notebook for Week 1](https://mybinder.org/v2/gh/ekmerchant/sts112/master?filepath=Week_1.ipynb)
- [RStudio Notebook and Lab for Week 1](https://rstudio.cloud/project/164154)

### Thursday 1.10.19: Introduction to the U.S. Census and R
- **Read before class:** Margo Anderson, 2008, [The Census, Audiences, and Publics](http://emilyklancher.com/teaching/Anderson.html), *Social Science History* 32: 1-18. *Note: This file takes some time to load and is best viewed in Safari. It includes a video clip that will not run in Chrome.*
- **Reference:** [Workflow Basics](https://r4ds.had.co.nz/workflow-basics.html) and [Data Transformation](https://r4ds.had.co.nz/transform.html) in Wickham and Grolemund.

$~$

## Week 2
### Tuesday 1.15.19: Introduction to IPUMS
- **Lab 1 due before class**

### Thursday 1.17.19: Working with IPUMS data
- **Before class:** Install [R](https://cran.cnr.berkeley.edu/) and [RStudio](https://www.rstudio.com/products/rstudio/download/). You will need to install R before you install RStudio. For RStudio, be sure to get the free version of RStudio Desktop. If you would like to see the process on a mac, watch [this video](https://youtu.be/EmZqlcKkJMM).
- **Read before class:** [Special issue of *Historical Methods* on the Minnesota historical census projects](readings/Minnesota_Historical_Census.pdf) (highlighted sections only).
- **Reference:** [Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html) in Wickham and Grolemund.

#### [Notebook 2](r_files/Notebook2.nb.html) | [Lab 2](r_files/Lab2.nb.html)

$~$

## Week 3
### Tuesday 1.22.19: Race formation in the U.S. Census
- **Lab 2 due before class**

### Thursday 1.24.19: Two-way tables
- **Read before class:** Jennifer L. Hochschild and Brenna Marea Powell, 2008, [Racial Reorganization and the United States Census, 1850-1930: Mulattoes, Half-Breeds, Mixed Parentage, Hindoos, and the Mexican Race](https://doi.org/10.1017/S0898588X08000047), *Studies in American Political Development* 22: 59-96.
- **Reference:** [Data Transformation](https://r4ds.had.co.nz/transform.html) in Wickham and Grolemund.

#### [Notebook 3](r_files/Notebook3.nb.html) | [Lab 3](r_files/Lab3.nb.html)

$~$

## Week 4
### Tuesday 1.29.19: Occupational change in the U.S. Census
- **Lab 3 due before class**

### Thursday 1.31.19: Graphing data over time  
- **Read before class:** [Life in Industrial America](http://www.americanyawp.com/text/18-industrial-america/), The American Yawp.
- **Reference:** [Data Visualization](https://r4ds.had.co.nz/data-visualisation.html) and [Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html) in Wickham and Grolemund.

$~$

## Week 5
### Tuesday 2.5.19: Gender in the U.S. Census
- **Lab 4 due before class**  

### Thursday 2.7.19: Tracking women's labor force participation
- **Read before class:** Nancy Folbre and Marjorie Abel, 1989, [Women's Work and Women's Households: Gender Bias in the U.S. Census](https://www.jstor.org/stable/pdf/40970556.pdf), *Social Research* 56: 545-569.; Harriet B. Presser, 1998, [Decapitating the U.S. Census Bureau's "Head of Household": Feminist mobilization in the 1970s](https://www.tandfonline.com/doi/pdf/10.1080/135457098338356), *Feminist Economics* 4: 145-158.
- **Reference:** [Data Visualization](https://r4ds.had.co.nz/data-visualisation.html) and [Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html) in Wickham and Grolemund.

$~$

## Week 6
### Tuesday 2.12.19: European and Asian immigration and restriction 
- **Lab 5 due before class**  

### Thursday 2.14.19: Population pyramids
- **Read before class:** Mae M. Ngai, 1999, [The Architecture of Race in American Immigration Law: A Reexamination of the Immigration Act of 1924](https://www.jstor.org/stable/pdf/2567407.pdf), *Journal of American History* 86: 67-92.
- **Reference:** [Data Visualization](https://r4ds.had.co.nz/data-visualisation.html) and [Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html) in Wickham and Grolemund.

$~$

## Week 7
### Tuesday 2.12.19: The Great Migration  
- **Lab 6 due before class**  

### Thursday 2.14.19: Mapping population
- **Read before class:** James N. Gregory, 2005, Chapter 1: A Century of Migration. Pp. 11-42 in [*The Southern Diaspora: How the Great Migrations of Black and White Southerners Transformed America*](http://ebookcentral.proquest.com/lib/ucdavis/detail.action?docID=413303) (Chapel Hill: University of North Carolina Press).

$~$

## Week 8
### Tuesday 2.26.19: Civil rights and race statistics  
- **Lab 7 due before class**  

### Thursday 2.28.19: Income analysis
- **Read before class:** Victoria Hattam, 2006, [Ethnicity and the Boundaries of Race: Rereading Directive 15](https://www.jstor.org/stable/20027961), *Daedalus* 134: 61-69; Mignon Duffy, 2007, [Doing the Dirty Work: Gender, Race, and Reproductive Labor in Historical Perspective](https://journals.sagepub.com/doi/pdf/10.1177/0891243207300764), *Gender and Society* 21: 313-336.
- **Reference:** [Data Visualization](https://r4ds.had.co.nz/data-visualisation.html) and [Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html) in Wickham and Grolemund.

$~$

## Week 9
### Tuesday 3.5.19: Families in the U.S. Census
- **Lab 8 due before class**

### Thursday 3.7.19: Family relationships  
- **Read before class:** Daniel T. Lichter and Zhenchao Qian, 2018, [Boundary Blurring? Racial Identification Among the Children of Interracial Couples](https://journals.sagepub.com/doi/pdf/10.1177/0002716218760507), *Annals of the American Academy of Political and Social Science* 677: 81-94.  
- **Reference:** [Relational Data](https://r4ds.had.co.nz/relational-data.html) in Wickham and Grolemund.

$~$

## Week 10
### Tuesday 3.12.19: Nontraditional families  
- **Lab 9 due before class**

### Thursday 3.14.19: Identifying same-sex families
- **Read before class:** Dan Black et al., 2007, [The Measurement of Same-Sex Unmarried Partner Couples in the 2000 U.S. Census](https://escholarship.org/uc/item/72r1q94b), California Center for Population Research.

#### Lab 10 due 3.21.19 at 12:30pm

